### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by rafleon** [benjisimon/app-doh#1]
What you have so far looks really interesting.

I'd like to help with app-doh, but I don't know git or github very well.

I wrote very similar code for a project that I am working on. it is an android app in kawa scheme with a main activity that is empty except for a few lines of code that loads other modules.

While getting my app to work, I developed some skill at diagnosing namespace and scope errors.  
Android apps are multi-threaded and call onCreate() repeatedly, so it took me a few days to figure out how to get it working.

Let me know what the status of this project is and what needs fixing.

**Comment by benjisimon** [comment]
Rafael -

I'm going to respond to you via e-mail. Suffice to say, I'm delighted to have you involved in this project!
